name: dio_http_formatter
description: A Dio interceptor for pretty printing the HTTP request/response to be printed in the console for easier debugging
version: 3.1.0
repository: https://github.com/assemmarwan/dio_http_formatter
homepage: https://github.com/assemmarwan/dio_http_formatter

environment:
  sdk: ^3.1.0

dependencies:
  dio: ^5.3.2
  logger: ^2.0.1

dev_dependencies:
  lints: ^2.1.1
  test: ^1.24.6
